services:
  postgres:
    image: postgres:17-alpine
    container_name: ride_connect_db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s

  db-reset:
    build: ./back-end
    container_name: ride_connect_db_reset
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - back-end/.env
    command: >
      sh -c "
      echo 'Aguardando inicializacao e conexao com o PostgreSQL...' &&
      npx prisma migrate reset --force &&
      echo 'Banco de dados PostgreSQL resetado, migracoes aplicadas e seeds inseridos com sucesso!'
      "

volumes:
  postgres-volume:
